apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  type: ClusterIP
  selector:
    app: cart-service
  ports:
    - name: http
      protocol: TCP
      port: 4004
      targetPort: 4004
