apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food-service
  template:
    metadata:
      labels:
        app: food-service
    spec:
      containers:
      - name: food-service
        image: 050752643680.dkr.ecr.us-east-1.amazonaws.com/food
        ports:
        - containerPort: 4002
