apiVersion: v1
kind: Service
metadata:
  name: food-service
spec:
  type: ClusterIP
  selector:
    app: food-service
  ports:
    - name: http
      protocol: TCP
      port: 4002
      targetPort: 4002
