name: Deploy Kubernetes Manifests to AWS EKS

on:
  push:
    branches:
      - main  # Thực hiện khi có sự thay đổi trên nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout mã nguồn từ repository

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.24.0'  # Cài đặt phiên bản kubectl

      - name: Update kubeconfig for EKS
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Deploy to EKS
        run: |
          kubectl apply -R -f https://github.com/codeweb2005/new-backend/tree/454c7ba6d2189d8efb3b393aeae710a51fe6053e/backend/  # Đảm bảo các manifest Kubernetes của bạn nằm trong thư mục k8s/
          
      - name: Verify deployment
        run: |
          kubectl get all  # Kiểm tra các tài nguyên trên Kubernetes sau khi triển khai
